### ISSUE TITLE
What are the dependencies for compiling it?

### ISSUE THREAD

**Issue by msmafra** [Ax9D/pw-viz#17]
What are the dependencies for compiling it? I am on Fedora and couldn't compile 0.16.
Is there a Docker image that I could set or grab to compile it?

**Comment by Ax9D** [comment]
You'll need the following,

Fedora:
```bash
dnf install pipewire pipewire-devel clang libxcb-devel
```
Arch:
```bash
pacman -S pipewire pkg-config clang libxcb
```

I will make a note for dependencies in the readme

**Comment by msmafra** [comment]
Thank you kindly!
