### ISSUE TITLE
ports ending with a number >= 10 sorted after 1

### ISSUE THREAD

**Issue by Be-ing** [Ax9D/pw-viz#20]
`playback_AUX10` is sorted after `playback_AUX1` instead of `playback_AUX2`
![image](https://user-images.githubusercontent.com/9455094/150848145-37a4384f-b262-492e-9842-add2485963a7.png)

**Comment by Ax9D** [comment]
![image](https://user-images.githubusercontent.com/40864118/150944688-8d6190c6-fa49-4a1b-9b11-7715b7b236b4.png)
Fixed! Ports are now sorted in natural ordering.

**Comment by Be-ing** [comment]
Cool, thanks for the quick fix! The natord crate is neat. I'll probably have a use for it myself at some point.
