### ISSUE TITLE
Panic on Zoom disconnect

### ISSUE THREAD

**Issue by BartMassey** [Ax9D/pw-viz#21]
`pw-viz` panics on Zoom disconnect on my box (Debian unstable pipewire 0.3.42).

Upgrading the dependency on `simple_logger` to 2.1.0 and then rebuilding seems to fix it.

**Comment by BartMassey** [comment]
In general, doing a `cargo upgrade`, truncating the version numbers, and then building to update `Cargo.lock` seems like a thing that should be done at this point.

**Comment by Ax9D** [comment]
Fixed in [a4099e0](https://github.com/Ax9D/pw-viz/commit/a4099e00f24282a4267ef0f4f97a6b0e78fda825)
