### ISSUE TITLE
Support cycles

### ISSUE THREAD

**Issue by minijackson** [Ax9D/pw-viz#5]
Hello and thank you for this project, it looks great!

The only issue I've seen so far from my very limited testing, is that pw-viz does not support cycles. The usecase I had was using Ardour, an audio work station:

I have a session with two tracks (Top and Bottom in the screenshot), whose audio is routed to the Master bus, and the Master bus is then forwarded to the speakers.

Here's how it looks in Patchage:

![screenshot](https://user-images.githubusercontent.com/1200507/142257432-48c7480f-81ab-484a-80b7-283ab917c34d.png)

In pw-viz, the message `ERROR [pw_viz::ui::graph] Cycle detected` is displayed on the terminal.
Here's how it looks:

![20211117_19h10m28s_grim](https://user-images.githubusercontent.com/1200507/142257824-22f0441b-a83a-429e-833a-56bdb7be9428.png)

Thanks again!

**Comment by skryking** [comment]
I see the same thing with Ardour as well.

**Comment by jansol** [comment]
Calfjackhost also exposes all plugins as one node, which necessitates looping back to the same node (patchage):

![image](https://user-images.githubusercontent.com/2588851/142429602-f2d73140-2873-4cf8-b4ae-48d59ab4751b.png)

**Comment by Ax9D** [comment]
I made some changes in the [grouped_nodes](https://github.com/Ax9D/pw-viz/tree/grouped_nodes) branch, seems to be working
![image](https://user-images.githubusercontent.com/40864118/142465241-8376268a-edae-49f0-a928-757391a6a459.png)

**Comment by jansol** [comment]
Nice! May I suggest making the link curves protrude from the ports a bit more aggressively? They turn behind the nodes rather quickly now, if they made a slightly bigger loop before disappearing that might help with readability a bit. Also if it's easily possible to make the nodes slightly transparent without hurting the readability that would help with following links that pass behind nodes.

**Comment by Ax9D** [comment]
Support for cycles was added in 415a619, although i'll keep this issue open till the next release
